/**
 * Changelog Generator - Auto-generates CHANGELOG.md from git commits
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { getCommitsSinceTag, categorizeCommits, getCurrentVersion } from './manager.js';

function git(cmd, root) {
  try {
    return execSync(`git ${cmd}`, { cwd: root, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

/**
 * Get all git tags sorted by version
 */
function getTags(root) {
  const output = git('tag --sort=-v:refname', root);
  if (!output) return [];
  return output.split('\n').filter(t => /^v?\d+\.\d+\.\d+/.test(t));
}

/**
 * Format a single commit for changelog
 */
function formatCommit(commit, root) {
  const shortHash = commit.hash.slice(0, 7);
  const subject = commit.subject;

  // Extract scope and message
  const scopeMatch = subject.match(/^(\w+)(\(.+?\))?:\s*(.+)/);
  if (scopeMatch) {
    const [, type, scope, message] = scopeMatch;
    const scopeStr = scope ? `**${scope.slice(1, -1)}**` : '';
    return `- ${scopeStr}${scopeStr ? ': ' : ''}${message} (\`${shortHash}\`)`;
  }

  return `- ${subject} (\`${shortHash}\`)`;
}

/**
 * Generate a version section for the changelog
 */
function generateVersionSection(version, commits, date) {
  const categories = categorizeCommits(commits);
  const lines = [];

  lines.push(`## [${version}] - ${date}`);
  lines.push('');

  if (categories.breaking.length > 0) {
    lines.push('### BREAKING CHANGES');
    lines.push('');
    for (const commit of categories.breaking) {
      lines.push(formatCommit(commit));
    }
    lines.push('');
  }

  if (categories.features.length > 0) {
    lines.push('### Features');
    lines.push('');
    for (const commit of categories.features) {
      lines.push(formatCommit(commit));
    }
    lines.push('');
  }

  if (categories.fixes.length > 0) {
    lines.push('### Bug Fixes');
    lines.push('');
    for (const commit of categories.fixes) {
      lines.push(formatCommit(commit));
    }
    lines.push('');
  }

  if (categories.performance.length > 0) {
    lines.push('### Performance');
    lines.push('');
    for (const commit of categories.performance) {
      lines.push(formatCommit(commit));
    }
    lines.push('');
  }

  if (categories.docs.length > 0) {
    lines.push('### Documentation');
    lines.push('');
    for (const commit of categories.docs) {
      lines.push(formatCommit(commit));
    }
    lines.push('');
  }

  if (categories.tests.length > 0) {
    lines.push('### Tests');
    lines.push('');
    for (const commit of categories.tests) {
      lines.push(formatCommit(commit));
    }
    lines.push('');
  }

  if (categories.other.length > 0) {
    lines.push('### Other');
    lines.push('');
    for (const commit of categories.other) {
      lines.push(formatCommit(commit));
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate full CHANGELOG.md
 */
export function generateChangelog(root, version) {
  const today = new Date().toISOString().split('T')[0];
  const commits = getCommitsSinceTag(root);
  const tags = getTags(root);

  const lines = [];

  // Header
  lines.push('# Changelog');
  lines.push('');
  lines.push('All notable changes to APIX Gateway will be documented in this file.');
  lines.push('Format based on [Keep a Changelog](https://keepachangelog.com/).');
  lines.push('');

  // Current version section
  if (commits.length > 0) {
    lines.push(generateVersionSection(version, commits, today));
    lines.push('---');
    lines.push('');
  }

  // Previous versions from tags
  for (const tag of tags) {
    const tagVersion = tag.replace(/^v/, '');
    const tagDate = git(`log -1 --format=%aI ${tag}`, root);
    const dateStr = tagDate ? tagDate.split('T')[0] : 'unknown';

    // Get commits between this tag and the previous one
    const tagIndex = tags.indexOf(tag);
    const prevTag = tags[tagIndex + 1];
    const range = prevTag ? `${prevTag}..${tag}` : tag;

    const logFormat = '%H|||%s|||%an|||%aI';
    const logOutput = git(`log ${range} --format="${logFormat}"`, root);

    if (logOutput) {
      const tagCommits = logOutput.split('\n').filter(Boolean).map(line => {
        const [hash, subject, author, date] = line.split('|||');
        return { hash, subject, author, date };
      });

      lines.push(generateVersionSection(tagVersion, tagCommits, dateStr));
      lines.push('---');
      lines.push('');
    }
  }

  // Footer
  lines.push('*Auto-generated by APIX Gateway CLI*');
  lines.push('');

  const changelogPath = path.join(root, 'CHANGELOG.md');
  fs.writeFileSync(changelogPath, lines.join('\n'));
  return changelogPath;
}
